# Generated by Django 5.2 on 2025-04-18 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание мероприятия"
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(verbose_name="Дата и время проведения"),
                ),
                (
                    "available_tickets",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество билетов",
                    ),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Цена билета",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Мероприятие",),
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-event_date", "title"],
            },
        ),
    ]
