# Generated by Django 5.2 on 2025-04-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_date"], name="events_even_event_d_2c2da5_idx"
            ),
        ),
    ]
