# Generated by Django 5.2 on 2025-04-19 19:34

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_events_even_event_d_2c2da5_idx"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="event",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Мероприятие удалено"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_deleted"], name="events_even_is_dele_59021f_idx"
            ),
        ),
    ]
