# Generated by Django 5.2 on 2025-04-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_managers_event_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-event_date", "title"],
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelManagers(
            name="event",
            managers=[],
        ),
    ]
